CREATE TABLE Payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payment_key VARCHAR(100) NOT NULL UNIQUE,
  order_id VARCHAR(100) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  status ENUM('READY', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'CANCELED') NOT NULL,
  payment_data JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 